# -*- coding: UTF-8 -*-

import unittest
from learning.test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner as HTMLTestRunner

if __name__ == "__main__":
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    with open('HTMLReport.html', 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title="MathFunc Test Report",
                                description="generated by HTMLRTestRunner.",
                                verbosity=2)
        runner.run(suite)